@echo off
setlocal EnableExtensions

REM ============================================================
REM .gitignore Updater
REM
REM Put this BAT in the root of an Unreal Engine plugin.
REM Running it will overwrite:
REM     <PluginRoot>\.gitignore
REM
REM This uses the standard Unreal/Visual Studio ignore rules
REM plus the local Release folder.
REM ============================================================

pushd "%~dp0"

set "PLUGIN_ROOT=%CD%"
set "GITIGNORE_FILE=%PLUGIN_ROOT%\.gitignore"

echo.
echo ============================================================
echo .gitignore Updater
echo ============================================================
echo.
echo Plugin Root:
echo %PLUGIN_ROOT%
echo.
echo Target:
echo %GITIGNORE_FILE%
echo.

echo Writing standard .gitignore...

> "%GITIGNORE_FILE%" echo # Visual Studio 2015 user specific files
>>"%GITIGNORE_FILE%" echo .vs/
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Compiled Object files
>>"%GITIGNORE_FILE%" echo *.slo
>>"%GITIGNORE_FILE%" echo *.lo
>>"%GITIGNORE_FILE%" echo *.o
>>"%GITIGNORE_FILE%" echo *.obj
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Precompiled Headers
>>"%GITIGNORE_FILE%" echo *.gch
>>"%GITIGNORE_FILE%" echo *.pch
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Compiled Dynamic libraries
>>"%GITIGNORE_FILE%" echo *.so
>>"%GITIGNORE_FILE%" echo *.dylib
>>"%GITIGNORE_FILE%" echo *.dll
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Fortran module files
>>"%GITIGNORE_FILE%" echo *.mod
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Compiled Static libraries
>>"%GITIGNORE_FILE%" echo *.lai
>>"%GITIGNORE_FILE%" echo *.la
>>"%GITIGNORE_FILE%" echo *.a
>>"%GITIGNORE_FILE%" echo *.lib
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Executables
>>"%GITIGNORE_FILE%" echo *.exe
>>"%GITIGNORE_FILE%" echo *.out
>>"%GITIGNORE_FILE%" echo *.app
>>"%GITIGNORE_FILE%" echo *.ipa
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # These project files can be generated by the engine
>>"%GITIGNORE_FILE%" echo *.xcodeproj
>>"%GITIGNORE_FILE%" echo *.xcworkspace
>>"%GITIGNORE_FILE%" echo *.sln
>>"%GITIGNORE_FILE%" echo *.suo
>>"%GITIGNORE_FILE%" echo *.opensdf
>>"%GITIGNORE_FILE%" echo *.sdf
>>"%GITIGNORE_FILE%" echo *.VC.db
>>"%GITIGNORE_FILE%" echo *.VC.opendb
>>"%GITIGNORE_FILE%" echo .vsconfig
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Precompiled Assets
>>"%GITIGNORE_FILE%" echo SourceArt/**/*.png
>>"%GITIGNORE_FILE%" echo SourceArt/**/*.tga
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Binary Files
>>"%GITIGNORE_FILE%" echo Binaries/*
>>"%GITIGNORE_FILE%" echo Plugins/**/Binaries/*
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Builds
>>"%GITIGNORE_FILE%" echo Build/*
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Whitelist PakBlacklist-^<BuildConfiguration^>.txt files
>>"%GITIGNORE_FILE%" echo !Build/*/
>>"%GITIGNORE_FILE%" echo Build/*/**
>>"%GITIGNORE_FILE%" echo !Build/*/PakBlacklist*.txt
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Don't ignore icon files in Build
>>"%GITIGNORE_FILE%" echo !Build/**/*.ico
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Built data for maps
>>"%GITIGNORE_FILE%" echo *_BuiltData.uasset
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Configuration files generated by the Editor
>>"%GITIGNORE_FILE%" echo Saved/*
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Compiled source files for the engine to use
>>"%GITIGNORE_FILE%" echo Intermediate/*
>>"%GITIGNORE_FILE%" echo Plugins/**/Intermediate/*
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Cache files for the editor to use
>>"%GITIGNORE_FILE%" echo DerivedDataCache/*
>>"%GITIGNORE_FILE%" echo.
>>"%GITIGNORE_FILE%" echo # Local packaged plugin output
>>"%GITIGNORE_FILE%" echo Release/

if errorlevel 1 (
    echo.
    echo ERROR: Failed to write .gitignore.
    echo.
    popd
    pause
    exit /b 1
)

echo.
echo ============================================================
echo SUCCESS
echo .gitignore has been updated.
echo ============================================================
echo.

popd
pause
exit /b 0
